[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["ffmpeg", "python311"]

[deploy]
startCommand = "python main_bot.py"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
sleepApplication = false

[deploy.healthcheck]
type = "http"
path = "/health"
port = 8080
initialDelaySeconds = 15
periodSeconds = 30